/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */

#include "discreteintegrals.hpp"
#include "exponentialintegrals.hpp"
#include "filonintegral.hpp"
#include "gausslaguerrecosinepolynomial.hpp"
#include "gausslobattointegral.hpp"
#include "gaussianorthogonalpolynomial.hpp"
#include "gaussianquadratures.hpp"
#include "integral.hpp"
#include "kronrodintegral.hpp"
#include "momentbasedgaussianpolynomial.hpp"
#include "segmentintegral.hpp"
#include "simpsonintegral.hpp"
#include "tanhsinhintegral.hpp"
#include "trapezoidintegral.hpp"
#include "twodimensionalintegral.hpp"

